spring:
  application:
    name: BankInk
    
  jpa:
      hibernate.ddl-auto: update
      database: oracle
      database-platform: org.hibernate.dialect.OracleDialect
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@//localhost:1521/bd
      password: 
      username: 